Jpa
Stipaxa-hub/store pull request #4
Opened 2023-12-01 12:34 UTC by Stipaxa-hub

2023-12-01 13:17 UTC, okuzan requested changes

2023-12-01 13:17 UTC, okuzan commented on src/main/java/mate/project/store/entity/Book.java
> +@Where(clause = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = TRUE WHERE id = ?")
@Where(clause = "is_deleted = FALSE")
```

2023-12-01 13:17 UTC, okuzan commented on src/main/java/mate/project/store/service/impl/BookServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Can't find a book with id " + id));
create a private method for find or throw logic

2023-12-01 13:17 UTC, okuzan commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
make sure each file ends with exactly one empty line
![image](https://github.com/Stipaxa-hub/store/assets/49767049/31c6c6c2-a965-4e16-92a6-942735463d10)

2023-12-01 13:17 UTC, okuzan commented on src/main/java/mate/project/store/controller/BookController.java
> +
no empty line after class definition

2023-12-02 10:42 UTC, olekskov approved these changes

2023-12-13 09:44 UTC, merged