Criteria query
Stipaxa-hub/store pull request #5
Opened 2023-12-12 19:01 UTC by Stipaxa-hub

2023-12-12 19:39 UTC, okuzan requested changes

2023-12-12 19:39 UTC, okuzan commented on src/main/java/mate/project/store/repository/book/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
p - bad naming

2023-12-12 19:39 UTC, okuzan commented on src/main/java/mate/project/store/repository/book/BookSpecificationProviderManager.java
> +                .orElseThrow(() -> new RuntimeException(
entity not found exception

2023-12-12 19:39 UTC, okuzan commented on src/main/java/mate/project/store/repository/book/spec/AuthorSpecificationProvider.java
> +        return "authors";
extract constants everywhere

2023-12-12 19:39 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yaml
add newline where needed

2023-12-12 19:39 UTC, okuzan commented on src/main/java/mate/project/store/repository/book/BookSpecificationBuilder.java
> +                    .getSpecification(searchParametersDto.titles()));
constant

2023-12-12 19:39 UTC, okuzan commented on src/main/java/mate/project/store/controller/BookController.java
> +
no empty lines after class declaration

2023-12-14 10:02 UTC, kozhukhovsky approved these changes

2023-12-14 11:09 UTC, merged