Global exception handler and data validation
Stipaxa-hub/store pull request #6
Opened 2023-12-12 20:40 UTC by Stipaxa-hub

2023-12-13 10:19 UTC, Sanderfuck commented
Resolve conflicts 
![image](https://github.com/Stipaxa-hub/store/assets/63095184/ce1b1eb9-680b-4193-8778-159dc1cd342d)

2023-12-13 15:53 UTC, Sanderfuck requested changes
![image](https://github.com/Stipaxa-hub/store/assets/63095184/df69b422-5d51-4e65-b107-b93852dee786)
Resolve conflicts

2023-12-13 15:53 UTC, Sanderfuck commented on src/main/java/mate/project/store/dto/CreateBookRequestDto.java
>      private String description;
Too poor validation, improve it using more annotations

2023-12-14 11:08 UTC, kozhukhovsky approved these changes

2023-12-14 11:12 UTC, merged